modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{
    modId = 'letsdoaddon-structures',
    version = '1.1.0',
    displayName = "Let's Do Addon: Structures",
    description = "An addon for the Let's Do mod series that adds themed, let's do-like structures to the world.",
    logoFile = 'lets-do-addon-structures_pack.png',
    updateJSONURL = 'https://api.modrinth.com/updates/2PaVx3ow/forge_updates.json',
    authors = 'Ninjdai',
    displayURL = 'https://modrinth.com/datapack/lets-do-addon-structures'
  },
]
