modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
[[mods]]
  modId = 'letsdoaddonstructures'
  version = '1.5.1'
  displayName = "Let's Do Addon: Structures"
  description = "An addon for the Let's Do mod series that adds themed, let's do-like structures to the world."
  logoFile = 'pack.png'
  updateJSONURL = 'https://api.modrinth.com/updates/2PaVx3ow/forge_updates.json'
  authors = 'Ninjdai'
  displayURL = 'https://modrinth.com/datapack/lets-do-addon-structures'

[[dependencies.letdoaddonstructures]]
  modId="meadow"
  mandatory=true

[[dependencies.letsdoaddonstructures]]
  modId="vinery"
  mandatory=true
  versionRange="[1.4.7,)"

[[dependencies.letsdoaddonstructures]]
  modId="nethervinery"
  mandatory=true
  versionRange="[1.2.2,)"
