# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare datapack as a zip
        run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" ".gitignore" "README.md" "LICENSE"
        
      - name: Upload the datapack
        uses: actions/upload-artifact@v4.3.0
        with:
          # Artifact name
          name: letsdo-addon-structures-datapack
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.event.repository.name }}.zip
