name: Datapack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare datapack as a zip
        run: |
          zip -r ${{ github.event.repository.name }}-datapack-latest.zip . -x ".git/*" ".github/*" ".gitignore" "README.md" "LICENSE" "fabric.mod.json" "quilt.mod.json" "META-INF/*"
          zip -r ${{ github.event.repository.name }}-latest.jar . -x ".git/*" ".github/*" ".gitignore" "README.md" "LICENSE" "*.zip"

      - name: Upload the datapack
        uses: actions/upload-artifact@v4.3.0
        with:
          name: letsdo-addon-structures-datapack-latest
          path: ${{ github.event.repository.name }}-datapack-latest.zip
      - name: Upload the mod
        uses: actions/upload-artifact@v4.3.0
        with:
          name: letsdo-addon-structures-latest
          path: ${{ github.event.repository.name }}-latest.jar
